services:
  # The main application service (e.g., a Django or Flask app)
  app:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - redis
    # Environment variable to configure Celery broker URL
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "your_secure_password_2026"

  # The Celery worker service
  celery_worker:
    build: .
    command: celery -A testtaskproject worker --loglevel=info #
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
    environment: &celery_env
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"

  # Мониторинг Flower
  flower:
    build: .
    command: celery -A testtaskproject flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker
    environment: *celery_env

  # The Redis message broker and result backend service
  redis:
    image: "redis:6.2-alpine" # Use an official Redis image
    container_name: redis
    ports:
      - "6379:6379"